# Generated by Django 5.1.6 on 2025-02-27 14:17

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    Book = apps.get_model("bookstore", "Book")
    for row in Book.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("bookstore", "0002_remove_book_id_book_id_book"),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
