# Generated by Django 5.1.6 on 2025-02-27 14:17

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20250227_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id_book',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
